Repository ChilliHugger/The-Lords-Of-Midnight, pull requests merged in 2020-12, with the labels that each got.

#32 Add setup and build instructions for Windows platform
  .gitignore
  README.md
  main/midnight/.cocos-project.json
  main/midnight/CMakeLists.txt
  main/midnight/proj.win32/game.aps
  main/midnight/proj.win32/main.cpp
  main/midnight/src/library/inc/collections.h
  main/midnight/src/library/src/datatypes.cpp
  main/midnight/src/library/src/misc.cpp
  main/midnight/src/system/moonring.cpp
  main/midnight/src/system/resolutionmanager.h
  main/midnight/src/tme/base/collections.cpp
  main/midnight/src/tme/scenario/discoverymap.cpp
  main/midnight/src/tme/scenario/item_character.cpp
  main/midnight/src/tme/scenario/item_regiment.cpp
  main/midnight/src/tme/scenario/map.cpp
  main/midnight/src/tme/scenario/processor_battle.cpp
  main/midnight/src/tme/scenarios/ddr/ddr_character.cpp
  main/midnight/src/tme/scenarios/ddr/ddr_processor_battle.cpp
  main/midnight/src/ui/uielement.h
Labels: desktop, windows

#54 Feature/tidy up safe idt
  main/midnight/src/tme/base/collections.cpp
  main/midnight/src/tme/base/mxengine.cpp
  main/midnight/src/tme/base/mxentity.cpp
  main/midnight/src/tme/base/mxinfo.cpp
  main/midnight/src/tme/base/mxinterface.cpp
  main/midnight/src/tme/base/mxitem.cpp
  main/midnight/src/tme/base/variables.cpp
  main/midnight/src/tme/baseinc/info.h
  main/midnight/src/tme/baseinc/variables.h
  main/midnight/src/tme/scenario/info_object.cpp
  main/midnight/src/tme/scenario/item_character.cpp
  main/midnight/src/tme/scenario/item_place.cpp
  main/midnight/src/tme/scenario/item_regiment.cpp
  main/midnight/src/tme/scenario/item_routenode.cpp
  main/midnight/src/tme/scenario/item_stronghold.cpp
  main/midnight/src/tme/scenarios/ddr/ddr_character.cpp
  main/midnight/src/tme/scenarios/default/default_scenario.cpp
Labels: tech debt

#64 Feature/desktop resolution change
  docs/build_windows.md
  main/midnight/CMakeLists.txt
  main/midnight/proj.win32/game.rc
  main/midnight/src/AppDelegate.cpp
  main/midnight/src/extensions/CustomDirector.h
  main/midnight/src/frontend/language.h
  main/midnight/src/panels/panel_mainmenu.cpp
  main/midnight/src/panels/panel_options.cpp
  main/midnight/src/panels/panel_options.h
  main/midnight/src/panels/panel_splashscreen.cpp
  main/midnight/src/system/moonring.cpp
  main/midnight/src/system/moonring.h
  main/midnight/src/system/resolutionmanager.cpp
  main/midnight/src/system/resolutionmanager.h
  main/midnight/src/system/settingsmanager.cpp
  main/midnight/src/system/settingsmanager.h
  main/midnight/src/ui/uihelper.cpp
  main/midnight/src/ui/uihelper.h
  main/midnight/src/ui/uipanel.cpp
  main/midnight/src/ui/uipanel.h
Labels: desktop, feature
