Repository ChilliHugger/The-Lords-Of-Midnight, pull requests merged in 2022-04, with the labels that each got.

#94 Add Approach name to command window
  main/midnight/src/frontend/choose_id.h
  main/midnight/src/tme/tme.cpp
  main/midnight/src/ui/uicommandwindow.cpp
  main/midnight/src/ui/uicommandwindow.h
Labels: enhancement, ui

#98 Feature/tooltips and select lord
  main/midnight/src/landscaping/LandscapePeople.cpp
  main/midnight/src/landscaping/LandscapePeople.h
  main/midnight/src/panels/panel_look.cpp
  main/midnight/src/panels/panel_map_detailed.cpp
  main/midnight/src/panels/panel_map_detailed.h
  main/midnight/src/panels/panel_select.cpp
Labels: bug, enhancement

#100 Add Compass Gadget to panel_look
  main/midnight/src/frontend/language.h
  main/midnight/src/frontend/layout_id.h
  main/midnight/src/panels/panel_look.cpp
  main/midnight/src/panels/panel_look.h
  main/midnight/src/system/moonring.cpp
  main/midnight/src/ui/uicompass.cpp
  main/midnight/src/ui/uicompass.h
  main/midnight/src/ui/uielement.h
Labels: feature, ui

#102 Fix Windows build issues
  main/midnight/src/tme/scenario/item_character.cpp
  main/midnight/src/ui/characters/uisinglelord.cpp
  main/midnight/src/ui/uibookmenu.cpp
  main/midnight/src/ui/uicommandwindow.cpp
  main/midnight/src/ui/uicommandwindow.h
Labels: bug
